# Generated by Django 5.2.6 on 2025-11-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_rename_id_course_cid_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cid',
        ),
        migrations.AddField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
