# Generated by Django 5.2.6 on 2026-02-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_id_course_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration_unit',
            field=models.CharField(choices=[('hours', 'hours'), ('minutes', 'minutes')], default='hours', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_unit',
            field=models.CharField(choices=[('hours', 'hours'), ('minutes', 'minutes')], default='hours', max_length=20),
        ),
    ]
