# Generated by Django 5.2.6 on 2026-03-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_duration_unit_alter_course_duration_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
